
export const Data = [
    { id: 1, "Name": "Angular" },
    { id: 2, "Name": "Vue.js" },
    { id: 3, "Name": "Next JS" },
    { id: 4, "Name": "React JS" },
    { id: 5, "Name": "Ember JS" },
    { id: 6, "Name": "Svelte JS" },
    { id: 7, "Name": "Gatsby JS" },
    { id: 8, "Name": "Nuxt JS" },
    { id: 9, "Name": 'Bootstrap' },
    { id: 10, "Name": "Node" },
    { id: 11, "Name": "Spring boot" },
    { id: 12, "Name": "Express JS" },
    { id: 13, "Name": "Laravel" },
    { id: 14, "Name": "Micronaut" },
    { id: 15, "Name": "Mocha JS" },
    { id: 16, "Name": "Jasmine" },
    { id: 17, "Name": "Jest" },
]